name: BucoRide
description: A new Flutter application.
version: 1.0.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.5
  connectivity_plus: ^6.1.2
  carousel_slider: ^5.0.0
  firebase_auth: ^5.5.4
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_crashlytics: ^4.0.3
  flutter_google_places_sdk: ^0.4.2+1
  flutter_spinkit: ^5.2.1
  firebase_storage: ^12.4.1
  flutter_local_notifications: ^19.2.1
  flutter_speed_dial: ^7.0.0
  flutter_animate: ^4.5.2
  firebase_app_check: ^0.3.2+4
  font_awesome_flutter: ^10.8.0

  geolocator: ^13.0.2
  geoflutterfire_plus: ^0.0.32
  google_maps_flutter: ^2.3.2
  googlemaps_flutter_webservices: ^1.0.2

  geocoding: ^4.0.0
  get: ^4.6.6


  modal_bottom_sheet: ^3.0.0
  percent_indicator: ^4.2.4
  provider: ^6.1.1
  page_animation_transition: ^1.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.5
  uuid: ^4.5.1
  url_launcher: ^6.1.10
  get_it: 8.0.3
  flutter_secure_storage: ^9.2.4
  intl_phone_field: ^3.2.0
  smooth_page_indicator: ^1.0.0
  curved_labeled_navigation_bar: ^2.0.5
  image_picker: ^1.1.2
  google_sign_in: ^6.2.2
  flutter_rating_bar: ^4.0.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3 #flutter pub run flutter_launcher_icons:main


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/map/
    - assets/animations/

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo_with_name.png"
